Fix crash when SENTRY_ENABLED is undefined
Otherwise eval_bool is called on x where x is None, leading to
None.lower() which causes:

AttributeError: 'NoneType' object has no attribute 'lower'